DROP TABLE IF EXISTS issues;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS scores;
DROP TABLE IF EXISTS inquiry;

CREATE TABLE issues(
id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
question VARCHAR(256) NOT NULL,
description VARCHAR(256) NOT NULL,
answer1 VARCHAR(256) NOT NULL,
answer2 VARCHAR(256) NOT NULL,
answer3 VARCHAR(256) NOT NULL,
answer4 VARCHAR(256) NOT NULL,
answer INTEGER NOT NULL,
category VARCHAR(256) NOT NULL
);

CREATE TABLE users (
username VARCHAR(50) NOT NULL PRIMARY KEY,
password VARCHAR(500) NOT NULL,
authority enum('ADMIN', 'USER') NOT NULL
);

CREATE TABLE scores (
name VARCHAR(256) NOT NULL,
score INTEGER NOT NULL,
category VARCHAR(256) NOT NULL
);

CREATE TABLE inquiry (
title VARCHAR(256) NOT NULL,
summary VARCHAR(256) NOT NULL
);